/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Drinks;
import service.DrinksService;
/**
 *
 * @author SON.TH183823
 */
public class editDrinksFrame extends javax.swing.JFrame {

    /**
     * Creates new form editDrinks
     */
    Drinks drinks;
    DrinksService drinksService;
    public editDrinksFrame(int ID) {
        initComponents();
        this.setLocationRelativeTo(null);
        drinksService = new DrinksService();
        drinks = drinksService.getDrinksByID(ID);
        IDDrinksTextField.setText(String.valueOf(drinks.getIDdrinks()));
        nameDrinksTextField.setText(drinks.getName());
        priceDrinksTextField.setText(String.valueOf(drinks.getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IDDrinksTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameDrinksTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceDrinksTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");
        setPreferredSize(new java.awt.Dimension(310, 305));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 190, 108));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/huy.png"))); // NOI18N
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(34, 225, 80, 30);

        luuButton.setBackground(new java.awt.Color(255, 190, 108));
        luuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        luuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ok.png"))); // NOI18N
        luuButton.setText("Lưu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(luuButton);
        luuButton.setBounds(177, 225, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sửa Thông Tin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 207, 29);

        jPanel2.setBackground(new java.awt.Color(255, 216, 148));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Mã Số");

        IDDrinksTextField.setEditable(false);
        IDDrinksTextField.setBackground(new java.awt.Color(255, 190, 108));
        IDDrinksTextField.setText("1");
        IDDrinksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDDrinksTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên ");

        jLabel4.setText("Giá");

        jLabel5.setText("VNĐ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(priceDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(17, 63, 260, 149);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 35, 280, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/anhgo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 310, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDDrinksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDDrinksTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDDrinksTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if(nameDrinksTextField.getText().equals("")
            || priceDrinksTextField.getText().equals(""))
        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
        else{
            String pattern = "\\d$";
            Pattern r = Pattern.compile(pattern);
            Matcher m = r.matcher(priceDrinksTextField.getText());
            if(m.find()){
                drinks  = new Drinks();
                drinks.setIDdrinks(Integer.valueOf(IDDrinksTextField.getText()));
                drinks.setName(nameDrinksTextField.getText());
                drinks.setPrice(Integer.valueOf(priceDrinksTextField.getText()));
                drinksService.updateDrinks(drinks);
                JOptionPane.showMessageDialog(rootPane, "Sửa Thành Công!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Giá không hợp lệ!");
            }
        }
    }//GEN-LAST:event_luuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDDrinksTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField nameDrinksTextField;
    private javax.swing.JTextField priceDrinksTextField;
    // End of variables declaration//GEN-END:variables
}
