/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class ListEmployeeFrame extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    UserService userService;
    User user;
    public ListEmployeeFrame(int IDuser) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        defaultTableModel = new DefaultTableModel();
        userService = new UserService();
        user = userService.getUserByID(IDuser);
        defaultTableModel = (DefaultTableModel) EmployeeTable.getModel();

        List<User> listEmployee = userService.getAllEmployees();
        listEmployee.forEach((e) -> {
            defaultTableModel.addRow(new Object[]{e.getIDUser(),
                 e.getFullName(), e.getGender(), e.getDob(), 
                 e.getAddress(), e.getPhone()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditSalaryButton = new javax.swing.JButton();
        refeshButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");
        setPreferredSize(new java.awt.Dimension(770, 430));
        getContentPane().setLayout(null);

        EmployeeTable.setBackground(new java.awt.Color(255, 216, 148));
        EmployeeTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        EmployeeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EmployeeTable.setInheritsPopupMenu(true);
        EmployeeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(EmployeeTable);
        if (EmployeeTable.getColumnModel().getColumnCount() > 0) {
            EmployeeTable.getColumnModel().getColumn(0).setMinWidth(60);
            EmployeeTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            EmployeeTable.getColumnModel().getColumn(0).setMaxWidth(60);
            EmployeeTable.getColumnModel().getColumn(1).setMinWidth(200);
            EmployeeTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            EmployeeTable.getColumnModel().getColumn(1).setMaxWidth(200);
            EmployeeTable.getColumnModel().getColumn(2).setMinWidth(60);
            EmployeeTable.getColumnModel().getColumn(2).setPreferredWidth(60);
            EmployeeTable.getColumnModel().getColumn(2).setMaxWidth(60);
            EmployeeTable.getColumnModel().getColumn(3).setMinWidth(150);
            EmployeeTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            EmployeeTable.getColumnModel().getColumn(3).setMaxWidth(150);
            EmployeeTable.getColumnModel().getColumn(4).setMinWidth(150);
            EmployeeTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            EmployeeTable.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 71, 728, 244);

        BackButton.setBackground(new java.awt.Color(255, 190, 108));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Back.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(0, 0, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(248, 0, 490, 46);

        EditSalaryButton.setBackground(new java.awt.Color(255, 190, 108));
        EditSalaryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditSalaryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/salarymoney.png"))); // NOI18N
        EditSalaryButton.setText("Thông Tin Lương NV");
        EditSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSalaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditSalaryButton);
        EditSalaryButton.setBounds(10, 330, 210, 50);

        refeshButton.setBackground(new java.awt.Color(255, 190, 108));
        refeshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refeshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/refresh1.png"))); // NOI18N
        refeshButton.setText("Refresh");
        refeshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refeshButton);
        refeshButton.setBounds(600, 330, 134, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 748, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/anhgo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSalaryButtonActionPerformed
        // TODO add your handling code here:
        int row = EmployeeTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListEmployeeFrame.this, "Chọn một nhân viên để xem thông tin");
        } else {
            
            int IDUser = (Integer) EmployeeTable.getValueAt(row, 0);
            new SalaryEFrame(IDUser, user.getIDUser()).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_EditSalaryButtonActionPerformed

    private void refeshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<User> listEmployee = userService.getAllEmployees();
        listEmployee.forEach((e) -> {
            defaultTableModel.addRow(new Object[]{e.getIDUser(),
                 e.getFullName(), e.getGender(), e.getDob(), 
                 e.getAddress(), e.getPhone()});
        });
    }//GEN-LAST:event_refeshButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        String a = user.getRole().replaceAll("\\s","");
        if (a.equals("Admin")) {
            new MenuAdminFrame(user.getIDUser()).setVisible(true);
        }
        if (a.equals("Employee")) {
            new MenuEmployeeFrame(user.getIDUser()).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//      
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListEmployeeFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditSalaryButton;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refeshButton;
    // End of variables declaration//GEN-END:variables
}
