/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class ListEmployeeFrame extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    UserService userService;
    User user;
    public ListEmployeeFrame(int IDuser) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        defaultTableModel = new DefaultTableModel();
        userService = new UserService();
        user = userService.getUserByID(IDuser);
        defaultTableModel = (DefaultTableModel) EmployeeTable.getModel();

        List<User> listEmployee = userService.getAllEmployees();
        listEmployee.forEach((e) -> {
            defaultTableModel.addRow(new Object[]{e.getIDUser(),
                 e.getFullName(), e.getGender(), e.getDob(), 
                 e.getAddress(), e.getPhone()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditSalaryButton = new javax.swing.JButton();
        refeshButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Tên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        EmployeeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EmployeeTable.setInheritsPopupMenu(true);
        EmployeeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(EmployeeTable);
        if (EmployeeTable.getColumnModel().getColumnCount() > 0) {
            EmployeeTable.getColumnModel().getColumn(0).setMinWidth(60);
            EmployeeTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            EmployeeTable.getColumnModel().getColumn(0).setMaxWidth(60);
            EmployeeTable.getColumnModel().getColumn(1).setMinWidth(120);
            EmployeeTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            EmployeeTable.getColumnModel().getColumn(1).setMaxWidth(150);
            EmployeeTable.getColumnModel().getColumn(2).setMinWidth(60);
            EmployeeTable.getColumnModel().getColumn(2).setPreferredWidth(60);
            EmployeeTable.getColumnModel().getColumn(2).setMaxWidth(60);
            EmployeeTable.getColumnModel().getColumn(3).setMinWidth(100);
            EmployeeTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            EmployeeTable.getColumnModel().getColumn(3).setMaxWidth(100);
            EmployeeTable.getColumnModel().getColumn(4).setMinWidth(95);
            EmployeeTable.getColumnModel().getColumn(4).setPreferredWidth(95);
            EmployeeTable.getColumnModel().getColumn(4).setMaxWidth(95);
            EmployeeTable.getColumnModel().getColumn(5).setMinWidth(100);
            EmployeeTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            EmployeeTable.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        EditSalaryButton.setText("Thông Tin Lương NV");
        EditSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSalaryButtonActionPerformed(evt);
            }
        });

        refeshButton.setText("Refesh");
        refeshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditSalaryButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refeshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refeshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSalaryButtonActionPerformed
        // TODO add your handling code here:
        int row = EmployeeTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListEmployeeFrame.this, "Chọn một nhân viên để xem thông tin");
        } else {
            
            int IDUser = (Integer) EmployeeTable.getValueAt(row, 0);
            new SalaryEFrame(IDUser, user.getIDUser()).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_EditSalaryButtonActionPerformed

    private void refeshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<User> listEmployee = userService.getAllEmployees();
        listEmployee.forEach((e) -> {
            defaultTableModel.addRow(new Object[]{e.getIDUser(),
                 e.getFullName(), e.getGender(), e.getDob(), 
                 e.getAddress(), e.getPhone()});
        });
    }//GEN-LAST:event_refeshButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new MenuAdminFrame(user.getIDUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//      
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListEmployeeFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditSalaryButton;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refeshButton;
    // End of variables declaration//GEN-END:variables
}
