/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import model.User;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class LogInFrame extends javax.swing.JFrame {

    User user;
    UserService userService;

    /**
     * Creates new form LogIn
     */
    public LogInFrame() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        userNameTextField = new javax.swing.JTextField();
        LogInButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 250, 70, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Tài Khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 170, 80, 20);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 210, 80, 20);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField);
        PasswordField.setBounds(170, 210, 170, 20);

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTextField);
        userNameTextField.setBounds(170, 170, 170, 20);

        LogInButton.setText("Đăng Nhập");
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogInButton);
        LogInButton.setBounds(230, 250, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SON.TH183823\\Documents\\NetBeansProjects\\QLBHoop16\\loginOOP.jpeg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -10, 420, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
        if (userNameTextField.getText().equals("") || String.valueOf(PasswordField.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đủ thông tin đăng nhập! ");
        } else {
            userService = new UserService();
            List<User> listUserName = userService.getAllUser();
            int a = 2;
            for (User uname : listUserName) {
                String b = uname.getUserName().replaceAll("\\s", "");
                String c = uname.getPassword().replaceAll("\\s", "");
                if (userNameTextField.getText().equals(b)
                    && String.valueOf(PasswordField.getPassword()).equals(c)) {
                    String d = uname.getRole().replaceAll("\\s", "");

                    if (d.equals("Employee")) {
                        new MenuEmployeeFrame(uname.getIDUser()).setVisible(true);    
                        this.dispose();
                        a = 1;
                        break;
                    }
                    if (d.equals("Admin")) {
                        new MenuAdminFrame(uname.getIDUser()).setVisible(true);
                        this.dispose();
                        a = 1;
                        break;
                    }
                }
                a = 0;

            }
            if (a == 0) {
                JOptionPane.showMessageDialog(rootPane, "Sai tài khoản hoặc mật khẩu.");
            }

        }
    }//GEN-LAST:event_LogInButtonActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
