/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Drinks;
import model.User;
import service.DrinksService;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class ManageDrinksFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageDrinks
     */
    Drinks drinks;
    DrinksService drinksService;
    DefaultTableModel defaultTableModel;
    User u;
    UserService userService = new UserService();
    public ManageDrinksFrame(int IDuser) {
        initComponents();
        this.setLocationRelativeTo(null);
        u = userService.getUserByID(IDuser);
        drinksService = new DrinksService();
        defaultTableModel = (DefaultTableModel) DrinksTable1.getModel();
        List<Drinks> listD  = drinksService.getAllDrinks();
        listD.forEach((d) -> {
            defaultTableModel.addRow(new Object[]{d.getIDdrinks(), d.getName(), d.getPrice()+"đ"});
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchGoodsTextField = new javax.swing.JTextField();
        searchGoodsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrinksTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addDrinks = new javax.swing.JButton();
        editDrinks = new javax.swing.JButton();
        removeDrinksButton = new javax.swing.JButton();
        refeshButton6 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tên Đồ Uống");

        searchGoodsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGoodsTextFieldActionPerformed(evt);
            }
        });

        searchGoodsButton.setText("Tìm Kiếm");
        searchGoodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGoodsButtonActionPerformed(evt);
            }
        });
        searchGoodsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchGoodsButtonKeyPressed(evt);
            }
        });

        DrinksTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DrinksTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số", "Tên ", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DrinksTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(DrinksTable1);
        if (DrinksTable1.getColumnModel().getColumnCount() > 0) {
            DrinksTable1.getColumnModel().getColumn(0).setMinWidth(90);
            DrinksTable1.getColumnModel().getColumn(0).setPreferredWidth(90);
            DrinksTable1.getColumnModel().getColumn(0).setMaxWidth(90);
            DrinksTable1.getColumnModel().getColumn(1).setMinWidth(250);
            DrinksTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            DrinksTable1.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchGoodsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(searchGoodsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchGoodsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGoodsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Đồ Uống");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        addDrinks.setText("Thêm");
        addDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinksActionPerformed(evt);
            }
        });

        editDrinks.setText("Sửa");
        editDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDrinksActionPerformed(evt);
            }
        });

        removeDrinksButton.setText("Xóa");
        removeDrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDrinksButtonActionPerformed(evt);
            }
        });

        refeshButton6.setText("Refesh");
        refeshButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(refeshButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(removeDrinksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editDrinks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(editDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeDrinksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(refeshButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchGoodsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGoodsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGoodsTextFieldActionPerformed

    private void searchGoodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGoodsButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        if (searchGoodsTextField.getText().equals("")) {

            List<Drinks> listD  = drinksService.getAllDrinks();
        listD.forEach((d) -> {
            defaultTableModel.addRow(new Object[]{d.getIDdrinks(), d.getName(), d.getPrice()});
        });
        }else{
            String a= searchGoodsTextField.getText().replaceAll("\\s","");
            List<Drinks> listD  = drinksService.getDrinksByName(a);
        listD.forEach((d) -> {
            defaultTableModel.addRow(new Object[]{d.getIDdrinks(), d.getName(), d.getPrice()});
        });
        }
    }//GEN-LAST:event_searchGoodsButtonActionPerformed

    private void searchGoodsButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGoodsButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGoodsButtonKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = u.getRole().replaceAll("\\s","");
        if (a.equals("Admin")) {
            new MenuAdminFrame(u.getIDUser()).setVisible(true);
        }
        if (a.equals("Employee")) {
            new MenuEmployeeFrame(u.getIDUser()).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refeshButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshButton6ActionPerformed
        defaultTableModel.setRowCount(0);
        List<Drinks> listD  = drinksService.getAllDrinks();
        listD.forEach((d) -> {
            defaultTableModel.addRow(new Object[]{d.getIDdrinks(), d.getName(), d.getPrice()+"đ"});
        });
    }//GEN-LAST:event_refeshButton6ActionPerformed

    private void removeDrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDrinksButtonActionPerformed
        // TODO add your handling code here:
        int row = DrinksTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ManageDrinksFrame.this, "Bạn chưa chọn hàng nào!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(ManageDrinksFrame.this,
                    "Bạn chắc chắn muốn xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String IDDrinks = String.valueOf(DrinksTable1.getValueAt(row, 0));
                
                drinksService.removeDrinks(IDDrinks);
                defaultTableModel.setRowCount(0);
                List<Drinks> listD  = drinksService.getAllDrinks();
        listD.forEach((d) -> {
            defaultTableModel.addRow(new Object[]{d.getIDdrinks(), d.getName(), d.getPrice()});
        });
                JOptionPane.showMessageDialog(ManageDrinksFrame.this, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_removeDrinksButtonActionPerformed

    private void addDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinksActionPerformed
        new addDrinksFrame().setVisible(true);
        
    }//GEN-LAST:event_addDrinksActionPerformed

    private void editDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDrinksActionPerformed
       int row = DrinksTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ManageDrinksFrame.this, "Bạn chưa chọn hàng nào!");
        } else {
            
            int ID = (Integer) DrinksTable1.getValueAt(row, 0);
            new editDrinksFrame(ID).setVisible(true);
            
        }
    }//GEN-LAST:event_editDrinksActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DrinksTable1;
    private javax.swing.JButton addDrinks;
    private javax.swing.JButton editDrinks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refeshButton6;
    private javax.swing.JButton removeDrinksButton;
    private javax.swing.JButton searchGoodsButton;
    private javax.swing.JTextField searchGoodsTextField;
    // End of variables declaration//GEN-END:variables
}
