
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Goods;
import model.User;
import service.GoodsService;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class ManageGoodsFrame extends javax.swing.JFrame {
    Goods goods;
    GoodsService goodsService;
    DefaultTableModel defaultTableModel;
    User u;
    UserService userService = new UserService();
    
    public ManageGoodsFrame(int IDuser) {
        initComponents();
        this.setLocationRelativeTo(null);
        u = userService.getUserByID(IDuser);
        goodsService = new GoodsService();
        defaultTableModel = new DefaultTableModel();  
        defaultTableModel = (DefaultTableModel) GoodsTable1.getModel();
        List<Goods> goodses  = goodsService.getAllGoods();
        goodses.forEach((goods) -> {
            int TotalMoney = goods.getAmount()*goods.getPrice();
            defaultTableModel.addRow(new Object[]{goods.getIDGoods(),goods.getNameGoods(),
                goods.getPrice(),goods.getAmount(),goods.getImportDate(),TotalMoney});
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchGoodsTextField = new javax.swing.JTextField();
        searchGoodsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GoodsTable1 = new javax.swing.JTable();
        RefeshButton5 = new javax.swing.JButton();
        removeGoodsButton4 = new javax.swing.JButton();
        editGoodsButton3 = new javax.swing.JButton();
        addGoodsButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Hàng Hóa");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tên Hàng Hóa");

        searchGoodsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGoodsTextFieldActionPerformed(evt);
            }
        });

        searchGoodsButton.setText("Tìm Kiếm");
        searchGoodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGoodsButtonActionPerformed(evt);
            }
        });
        searchGoodsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchGoodsButtonKeyPressed(evt);
            }
        });

        GoodsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Số", "Tên ", "Giá", "Số Lượng", "Ngày Nhập", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GoodsTable1);
        if (GoodsTable1.getColumnModel().getColumnCount() > 0) {
            GoodsTable1.getColumnModel().getColumn(0).setMinWidth(50);
            GoodsTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            GoodsTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            GoodsTable1.getColumnModel().getColumn(1).setMinWidth(100);
            GoodsTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            GoodsTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            GoodsTable1.getColumnModel().getColumn(2).setMinWidth(70);
            GoodsTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
            GoodsTable1.getColumnModel().getColumn(3).setMinWidth(70);
            GoodsTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
            GoodsTable1.getColumnModel().getColumn(3).setMaxWidth(70);
            GoodsTable1.getColumnModel().getColumn(4).setMinWidth(100);
            GoodsTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            GoodsTable1.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchGoodsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(searchGoodsButton)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchGoodsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGoodsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RefeshButton5.setText("Refesh");
        RefeshButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefeshButton5ActionPerformed(evt);
            }
        });

        removeGoodsButton4.setText("Xóa");
        removeGoodsButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGoodsButton4ActionPerformed(evt);
            }
        });

        editGoodsButton3.setText("Sửa");
        editGoodsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGoodsButton3ActionPerformed(evt);
            }
        });

        addGoodsButton.setText("Thêm");
        addGoodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGoodsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addGoodsButton)
                        .addGap(129, 129, 129)
                        .addComponent(removeGoodsButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(editGoodsButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RefeshButton5)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeGoodsButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(addGoodsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RefeshButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editGoodsButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = u.getRole().replaceAll("\\s","");
        if (a.equals("Admin")) {
            new MenuAdminFrame(u.getIDUser()).setVisible(true);
        }
        if (a.equals("Employee")) {
            new MenuEmployeeFrame(u.getIDUser()).setVisible(true);
        }
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchGoodsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGoodsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGoodsTextFieldActionPerformed

    private void searchGoodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGoodsButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        if (searchGoodsTextField.getText().equals("")) {
            
        List<Goods> goodses  = goodsService.getAllGoods();
        goodses.forEach((goods) -> {
            int TotalMoney = goods.getAmount()*goods.getPrice();
            defaultTableModel.addRow(new Object[]{goods.getIDGoods(),goods.getNameGoods(),
                goods.getPrice(),goods.getAmount(),goods.getImportDate(),TotalMoney});
        });
        }else{
           String a= searchGoodsTextField.getText().replaceAll("\\s","");
            List<Goods> goodses  = goodsService.getGoodsByName(a);
            goodses.forEach((goods) -> {
            int TotalMoney = goods.getAmount()*goods.getPrice();
            defaultTableModel.addRow(new Object[]{goods.getIDGoods(),goods.getNameGoods(),
                goods.getPrice(),goods.getAmount(),goods.getImportDate(),TotalMoney});
        });
        }
    }//GEN-LAST:event_searchGoodsButtonActionPerformed

    private void RefeshButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefeshButton5ActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<Goods> goodses  = goodsService.getAllGoods();
        goodses.forEach((goods) -> {
            int TotalMoney = goods.getAmount()*goods.getPrice();
            defaultTableModel.addRow(new Object[]{goods.getIDGoods(),goods.getNameGoods(),
                goods.getPrice(),goods.getAmount(),goods.getImportDate(),TotalMoney});
        });
    }//GEN-LAST:event_RefeshButton5ActionPerformed

    private void addGoodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGoodsButtonActionPerformed
        // TODO add your handling code here:
        new addGoodsFrame(u.getIDUser()).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_addGoodsButtonActionPerformed

    private void removeGoodsButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGoodsButton4ActionPerformed
        // TODO add your handling code here:
        int row = GoodsTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ManageGoodsFrame.this, "Bạn chưa chọn hàng nào!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(ManageGoodsFrame.this,
                    "Bạn chắc chắn muốn xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String IDGoods = String.valueOf(GoodsTable1.getValueAt(row, 0));
                goodsService.removeGoods(IDGoods);
                defaultTableModel.setRowCount(0);
                List<Goods> listGoods = goodsService.getAllGoods();
                listGoods.forEach((goods) -> {
                    int TotalMoney = goods.getAmount()*goods.getPrice();
            defaultTableModel.addRow(new Object[]{goods.getIDGoods(),goods.getNameGoods(),
                goods.getPrice(),goods.getAmount(),goods.getImportDate(),TotalMoney});
        });
                JOptionPane.showMessageDialog(ManageGoodsFrame.this, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_removeGoodsButton4ActionPerformed

    private void searchGoodsButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchGoodsButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGoodsButtonKeyPressed

    private void editGoodsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGoodsButton3ActionPerformed
        // TODO add your handling code here:
        int row = GoodsTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ManageGoodsFrame.this, "Bạn chưa chọn hàng nào!");
        } else {
            
            int IDgoods = (Integer) GoodsTable1.getValueAt(row, 0);
                new editGoodsFrame(IDgoods,u.getIDUser()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_editGoodsButton3ActionPerformed

//        public static void main(String args[]) {
//     
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageGoodsFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GoodsTable1;
    private javax.swing.JButton RefeshButton5;
    private javax.swing.JButton addGoodsButton;
    private javax.swing.JButton editGoodsButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeGoodsButton4;
    private javax.swing.JButton searchGoodsButton;
    private javax.swing.JTextField searchGoodsTextField;
    // End of variables declaration//GEN-END:variables
}
