/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import service.UserService;

/**
 *
 * @author SON.TH183823
 */
public class SalaryEFrame extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    UserService userService;
    User user , u;
    /**
     * Creates new form ListEmployeeFrame
     */
    public SalaryEFrame(int IDUser, int IDU0) {
        initComponents();
        this.setLocationRelativeTo(null);
        defaultTableModel = new DefaultTableModel();
        userService = new UserService();
        user = userService.getUserByID(IDUser);
        u = userService.getUserByID(IDU0);
        
        defaultTableModel = (DefaultTableModel) SalaryETable.getModel();

        IDuserTextField.setText(IDUser+"");
        List<User> listEmployee = userService.getSalaryEmployeeByID(IDUser);
        listEmployee.forEach((e) -> {
            int a = e.getTotalShiftOnMonth()*e.getMoneyShift()*(100+e.getBonus())/100;
            fullNameTextField.setText(e.getFullName());
            defaultTableModel.addRow(new Object[]{e.getMonth(),
                  e.getShift(), e.getTotalShiftOnMonth(), 
                 e.getMoneyShift(), e.getBonus(),a+"đ"
               });
        });

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalaryETable = new javax.swing.JTable();
        fullNameTextField = new javax.swing.JTextField();
        EditButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IDuserTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Hàng");
        setPreferredSize(new java.awt.Dimension(735, 390));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Lương Nhân Viên");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(211, 0, 370, 46);

        BackButton.setBackground(new java.awt.Color(255, 190, 108));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Back.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(0, 0, 100, 33);

        jPanel1.setBackground(new java.awt.Color(255, 216, 148));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SalaryETable.setBackground(new java.awt.Color(255, 216, 148));
        SalaryETable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SalaryETable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Ca Làm", "Tổng Ca", "Số Tiền/Ca", "Bonus", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SalaryETable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        SalaryETable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalaryETable.setInheritsPopupMenu(true);
        SalaryETable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(SalaryETable);
        if (SalaryETable.getColumnModel().getColumnCount() > 0) {
            SalaryETable.getColumnModel().getColumn(0).setMinWidth(60);
            SalaryETable.getColumnModel().getColumn(0).setPreferredWidth(60);
            SalaryETable.getColumnModel().getColumn(0).setMaxWidth(60);
            SalaryETable.getColumnModel().getColumn(3).setMinWidth(100);
            SalaryETable.getColumnModel().getColumn(3).setPreferredWidth(100);
            SalaryETable.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        fullNameTextField.setEditable(false);
        fullNameTextField.setBackground(new java.awt.Color(255, 190, 108));
        fullNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        EditButton.setBackground(new java.awt.Color(255, 190, 108));
        EditButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/edit.png"))); // NOI18N
        EditButton.setText("Sửa");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Họ Tên");

        IDuserTextField.setEditable(false);
        IDuserTextField.setBackground(new java.awt.Color(255, 190, 108));
        IDuserTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IDuserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDuserTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã NV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDuserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDuserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 52, 700, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/anhgo.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 730, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new ListEmployeeFrame(u.getIDUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void IDuserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDuserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDuserTextFieldActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        int row = SalaryETable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(SalaryEFrame.this, "Bạn chưa chọn hàng nào!");
        } else {
            
            int IDUser =Integer.valueOf(IDuserTextField.getText());
            int Month;
            Month = (Integer)SalaryETable.getValueAt(row, 0);
            
            new EditSalaryFrame(IDUser,Month,u.getIDUser()).setVisible(true);
            this.dispose();
        }
        
    
    }//GEN-LAST:event_EditButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField IDuserTextField;
    private javax.swing.JTable SalaryETable;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
